env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:yml/base'
  - 'plugin:yml/recommended'
  - 'plugin:yml/standard'
  - 'plugin:yml/prettier'

overrides:
  - files: ["*.yaml", "*.yml"]
    parser: yaml-eslint-parser
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console:
    - warn
  yml/require-string-key: error
  yml/sort-keys: warn
ignorePatterns:
  - foundry/**/*.js
  - src/module/documents.ts
  - node_modules/**
  - data/**
  - dist/**
