env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console:
    - warn
ignorePatterns:
  - foundry/**/*.js
