env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:yml/base'
  - 'plugin:yml/recommended'
  - 'plugin:yml/standard'
  - 'plugin:yml/prettier'

overrides:
  - files: ["*.yaml", "*.yml"]
    parser: yaml-eslint-parser
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  "@typescript-eslint/lines-between-class-members":
    - warn
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
  "@typescript-eslint/prefer-as-const":
    - warn
  "@typescript-eslint/space-before-function-paren":
    - warn
    - anonymous: always
      asyncArrow: always
      named: never
  "@typescript-eslint/space-infix-ops":
    - warn
  eol-last:
    - error
  linebreak-style:
    - error
    - unix
  no-trailing-spaces:
    - error
  semi:
    - error
    - always
  spaced-comment:
    - error
    - always
    - exceptions: ["-", "*"]
      markers: [/]
  no-console:
    - warn
  yml/require-string-key: error
  yml/sort-keys: warn
ignorePatterns:
  - foundry/**/*.js
  - src/module/documents.ts
  - node_modules/**
  - data/**
  - dist/**
